# Generated by Django 3.2.3 on 2021-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngopages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoactivitymodel',
            name='document_list',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='registerngomodel',
            name='ngo_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ngoactivitymodel',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ngoactivitymodel',
            name='note_for_donner',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ngoactivitymodel',
            name='note_for_needy',
            field=models.TextField(max_length=1000),
        ),
    ]
